#!/bin/bash

mkdir -p ~/.vim/autoload ~/.vim/bundle && \
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

while read plugin; do
  cd ~/.vim/bundle
  [[ -d "$(basename $plugin)" ]] || git clone "https://github.com/$plugin"
done < $(dirname $0)/vim_plugins
